# https://gohugo.io/configuration/introduction/#configuration-directory

baseURL = 'https://eubiotic.localhost/'
# website title
title = 'Eubiotic'

# website copyright
copyright = 'EUBIOTIC<sup>®</sup> este marca inregistrata a Labormed – O companie Zentiva | Toate drepturile rezervate'

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = 'ro'

# language code ["en", "zh-CN", "fr", "pl", ...]
locale = 'ro-RO'

# all languages are generated in folders
defaultContentLanguageInSubdir = false

# language name ["English", "简体中文", "Français", "Polski", ...]
label = 'Română'

# this is used to bail out of recursive content generation
timeout = '1000s'

# cleans the destination dir before building
cleanDestinationDir = true

# whether to use robots.txt
enableRobotsTXT = true

# to make the .Lastmod function work
enableGitInfo = false

# whether to show the table of contents in the article
tableOfContents = true

# whether to show the framework used in header
disableHugoGeneratorInject  = true

# whether to use emoji code
enableEmoji = true

# transliterate non-ASCII characters when generating URLs
removePathAccents = true

# the minimum number of words returned by the Summary
summaryLength = 20
