# Documentation: https://gohugo.io/configuration/permalinks/

[[permalinks]]
pattern = "/:slugorcontentbasename/"
[permalinks.target]
kind = "{page,section}"
path = "{/basic-page,/basic-page/**,/static-page,/static-page/**}"

[[permalinks]]
pattern = "/gama-eubiotic/:slugorcontentbasename/"
[permalinks.target]
kind = "{page}"
path = "{/product/**}"

[[permalinks]]
pattern = "/intrebari-frecvente-despre-eubiotic/:slugorcontentbasename/"
[permalinks.target]
kind = "{page}"
path = "{/faq/**}"
