# Documentation: https://gohugo.io/configuration/permalinks/

[[permalinks]]
pattern = "/:slugorcontentbasename/"
[permalinks.target]
kind = "{page,section}"
path = "{/basic-page,/basic-page/**,/static-page,/static-page/**}"
