# Main Menu
[[main]]
name        = 'Acasă'
url         = ''
pre         = ''
post        = ''
title       = 'Acasă'
parent      = ''
pageRef     = '/'
identifier  = 'home'
weight      = 10

[[main]]
name        = 'Despre'
url         = '/despre/eubiotic/'
pre         = ''
post        = ''
title       = 'Despre Eubiotic'
parent      = ''
pageRef     = ''
identifier  = 'about'
weight      = 20

[[main]]
name        = 'Despre Eubiotic®'
url         = ''
pre         = ''
post        = ''
title       = 'Despre Eubiotic®'
parent      = 'about'
pageRef     = 'despre-eubiotic'
identifier  = 'despre-eubiotic'
weight      = 21

[[main]]
name        = 'Microbiomul'
url         = ''
pre         = ''
post        = ''
title       = 'Microbiomul'
parent      = 'about'
pageRef     = 'microbiom'
identifier  = 'microbiom'
weight      = 22

[[main]]
name        = 'Diaree'
url         = ''
pre         = ''
post        = ''
title       = 'Diaree'
parent      = 'about'
pageRef     = 'diaree'
identifier  = 'diarrhea'
weight      = 23

[[main]]
name        = 'Constipație'
url         = ''
pre         = ''
post        = ''
title       = 'Constipație'
parent      = 'about'
pageRef     = 'constipatie'
identifier  = 'constipatie'
weight      = 24

[[main]]
name        = 'Colici'
url         = ''
pre         = ''
post        = ''
title       = 'Colici'
parent      = 'about'
pageRef     = 'colici'
identifier  = 'colici'
weight      = 25

[[main]]
name        = 'Balonare'
url         = ''
pre         = ''
post        = ''
title       = 'Balonare'
parent      = 'about'
pageRef     = 'balonare'
identifier  = 'balonare'
weight      = 26

[[main]]
name        = 'Gama Eubiotic'
url         = ''
pre         = ''
post        = ''
title       = 'Gama Eubiotic'
parent      = ''
pageRef     = 'product'
identifier  = 'product'
weight      = 30

[[main]]
name        = 'Podcast'
url         = ''
pre         = ''
post        = ''
title       = 'Podcast'
parent      = ''
pageRef     = 'podcast'
identifier  = 'podcast'
weight      = 40

[[main]]
name        = 'Blog'
url         = ''
pre         = ''
post        = ''
title       = 'Blog'
parent      = ''
pageRef     = 'blog'
identifier  = 'blog'
weight      = 50

[[main]]
name        = 'Farmacovigilență'
url         = ''
pre         = ''
post        = ''
title       = 'Farmacovigilență'
parent      = ''
pageRef     = 'farmacovigilenta'
identifier  = 'pharmacovigilance'
weight      = 60

[[main]]
name        = 'Cumpără'
url         = ''
pre         = ''
post        = ''
title       = 'Cumpără'
parent      = ''
pageRef     = 'cumpara'
identifier  = 'buy'
weight      = 70

[[main]]
name        = 'Contact'
url         = ''
pre         = ''
post        = ''
title       = 'Contact'
parent      = ''
pageRef     = 'contact'
identifier  = 'contact'
weight      = 80
