# Main Menu
[[main]]
name        = 'Acasă'
url         = ''
pre         = ''
post        = ''
title       = 'Acasă'
parent      = ''
pageRef     = '/'
identifier  = 'home'
weight      = 10

[[main]]
name        = 'Despre'
url         = ''
pre         = ''
post        = ''
title       = 'Despre Eubiotic'
parent      = ''
pageRef     = 'despre-eubiotic'
identifier  = 'about'
weight      = 20

[[main]]
name        = 'Despre Eubiotic<sup>®</sup>'
url         = ''
pre         = ''
post        = ''
title       = 'Despre Eubiotic®'
parent      = 'about'
pageRef     = 'despre-eubiotic'
identifier  = 'despre-eubiotic'
weight      = 21

[[main]]
name        = 'Microbiomul'
url         = ''
pre         = ''
post        = ''
title       = 'Microbiomul'
parent      = 'about'
pageRef     = 'microbiom'
identifier  = 'microbiom'
weight      = 22

[[main]]
name        = 'Diaree'
url         = ''
pre         = ''
post        = ''
title       = 'Diaree'
parent      = 'about'
pageRef     = 'diaree'
identifier  = 'diarrhea'
weight      = 23

[[main]]
name        = 'Constipație'
url         = ''
pre         = ''
post        = ''
title       = 'Constipație'
parent      = 'about'
pageRef     = 'constipatie'
identifier  = 'constipatie'
weight      = 24

[[main]]
name        = 'Colici'
url         = ''
pre         = ''
post        = ''
title       = 'Colici'
parent      = 'about'
pageRef     = 'colici'
identifier  = 'colici'
weight      = 25

[[main]]
name        = 'Balonare'
url         = ''
pre         = ''
post        = ''
title       = 'Balonare'
parent      = 'about'
pageRef     = 'balonare'
identifier  = 'balonare'
weight      = 26

[[main]]
name        = 'Gama Eubiotic'
url         = ''
pre         = ''
post        = ''
title       = 'Gama Eubiotic'
parent      = ''
pageRef     = 'product'
identifier  = 'product'
weight      = 30

[[main]]
name        = 'Eubiotic'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic'
parent      = 'product'
pageRef     = 'eubiotic'
identifier  = 'eubiotic'
weight      = 31

[[main]]
name        = 'Eubiotic Forte'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic Forte'
parent      = 'product'
pageRef     = 'eubiotic-forte'
identifier  = 'eubiotic-forte'
weight      = 32

[[main]]
name        = 'Eubiotic Imunoflu'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic Imunoflu'
parent      = 'product'
pageRef     = 'eubiotic-imunoflu'
identifier  = 'eubiotic-imunoflu'
weight      = 33

[[main]]
name        = 'Eubiotic Baby picături'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic Baby picături'
parent      = 'product'
pageRef     = 'eubiotic-baby-picaturi'
identifier  = 'eubiotic-baby-picaturi'
weight      = 34

[[main]]
name        = 'Eubiotic Baby'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic Baby'
parent      = 'product'
pageRef     = 'eubiotic-baby-stick-10'
identifier  = 'eubiotic-baby-stick-10'
weight      = 35

[[main]]
name        = 'Eubiotic Baby 20 Stick-uri'
url         = ''
pre         = ''
post        = ''
title       = 'Eubiotic Baby 20 Stick-uri'
parent      = 'product'
pageRef     = 'eubiotic-baby-stick-20'
identifier  = 'eubiotic-baby-stick-20'
weight      = 36

[[main]]
name        = 'Podcast'
url         = ''
pre         = ''
post        = ''
title       = 'Podcast'
parent      = ''
pageRef     = 'podcast'
identifier  = 'podcast'
weight      = 40

[[main]]
name        = 'Blog'
url         = ''
pre         = ''
post        = ''
title       = 'Blog'
parent      = ''
pageRef     = 'blog'
identifier  = 'blog'
weight      = 50

[[main]]
name        = 'Farmacovigilență'
url         = ''
pre         = ''
post        = ''
title       = 'Farmacovigilență'
parent      = ''
pageRef     = 'farmacovigilenta'
identifier  = 'farmacovigilenta'
weight      = 60

[[main]]
name        = 'Cumpără'
url         = ''
pre         = ''
post        = ''
title       = 'Cumpără'
parent      = ''
pageRef     = 'cumpara'
identifier  = 'cumpara'
weight      = 70

[[main]]
name        = 'Contact'
url         = 'https://zentiva.ro/contact'
pre         = ''
post        = ''
title       = 'Contact'
parent      = ''
pageRef     = ''
identifier  = 'contact'
weight      = 80

# Footer Menu
[[footer]]
name        = 'Gama Eubiotic'
url         = ''
pre         = ''
post        = ''
title       = 'Gama Eubiotic'
parent      = ''
pageRef     = 'product'
identifier  = 'footer-product'
weight      = 10

[[footer]]
name        = 'Cumpără'
url         = ''
pre         = ''
post        = ''
title       = 'Cumpără'
parent      = ''
pageRef     = 'cumpara'
identifier  = 'footer-buy'
weight      = 20

[[footer]]
name        = 'Contact'
url         = 'https://zentiva.ro/contact'
pre         = ''
post        = ''
title       = 'Contact'
parent      = ''
pageRef     = ''
identifier  = 'footer-contact'
weight      = 30

[[footer]]
name        = 'Microbiomul'
url         = ''
pre         = ''
post        = ''
title       = 'Microbiomul'
parent      = ''
pageRef     = 'microbiom'
identifier  = 'footer-microbiome'
weight      = 40

[[footer]]
name        = 'Diaree'
url         = ''
pre         = ''
post        = ''
title       = 'Diaree'
parent      = ''
pageRef     = 'diaree'
identifier  = 'footer-diarrhea'
weight      = 50

[[footer]]
name        = 'Constipație'
url         = ''
pre         = ''
post        = ''
title       = 'Constipație'
parent      = ''
pageRef     = 'constipatie'
identifier  = 'footer-constipation'
weight      = 60

[[footer]]
name        = 'Colici'
url         = ''
pre         = ''
post        = ''
title       = 'Colici'
parent      = ''
pageRef     = 'colici'
identifier  = 'footer-colic'
weight      = 70

[[footer]]
name        = 'Balonare'
url         = ''
pre         = ''
post        = ''
title       = 'Balonare'
parent      = ''
pageRef     = 'balonare'
identifier  = 'footer-bloating'
weight      = 80

[[footer]]
name        = 'Farmacovigilență'
url         = ''
pre         = ''
post        = ''
title       = 'Farmacovigilență'
parent      = ''
pageRef     = 'farmacovigilenta'
identifier  = 'footer-pharmacovigilance'
weight      = 90

# Legal Menu
[[legal]]
name        = 'Termeni și condiții'
url         = ''
pre         = ''
post        = ''
title       = 'Termeni și condiții'
parent      = ''
pageRef     = 'termeni-si-conditii'
identifier  = 'termeni-si-conditii'
weight      = 10

[[legal]]
name        = 'Politică de confidențialitate'
url         = ''
pre         = ''
post        = ''
title       = 'Politică de confidențialitate'
parent      = ''
pageRef     = 'politica-de-confidentialitate'
identifier  = 'politica-de-confidentialitate'
weight      = 20

[[legal]]
name        = 'Politica de cookie-uri'
url         = ''
pre         = ''
post        = ''
title       = 'Politica de cookie-uri'
parent      = ''
pageRef     = 'politica-de-cookies'
identifier  = 'politica-de-cookies'
weight      = 30

[[legal]]
name        = 'Schimbați preferințele cookie-urilor'
url         = '#manage-consent'
pre         = ''
post        = ''
title       = 'Schimbați preferințele cookie-urilor'
parent      = ''
pageRef     = ''
identifier  = 'manage-consent'
weight      = 40

# Social Menu
[[social]]
name        = 'Facebook'
url         = 'https://www.facebook.com/EUBIOTIC/'
pre         = 'facebook-icon'
post        = ''
title       = 'Facebook'
parent      = ''
pageRef     = ''
identifier  = 'facebook'
weight      = 10

[[social]]
name        = 'Instagram'
url         = 'https://www.instagram.com/_eubiotic/'
pre         = 'instagram-icon'
post        = ''
title       = 'Instagram'
parent      = ''
pageRef     = ''
identifier  = 'instagram'
weight      = 20

[[social]]
name        = 'LinkedIn'
url         = 'https://ro.linkedin.com/company/zentiva-romania'
pre         = 'linkedin-icon'
post        = ''
title       = 'LinkedIn'
parent      = ''
pageRef     = ''
identifier  = 'linkedin'
weight      = 30

[[social]]
name        = 'YouTube'
url         = 'https://www.youtube.com/@GamaEubiotic'
pre         = 'youtube-icon'
post        = ''
title       = 'YouTube'
parent      = ''
pageRef     = ''
identifier  = 'youtube'
weight      = 40
